'use strict';
const db = require('../src/config/database');

// columns: mes, modalidade, grupo, cota, parcela, cliente, valor_do_bem, assessor, email_assessor, escritorio, ano, natureza_sujeito, uf, tipo_produto, taxa_adm
const ROWS = [
  [1,null,null,null,null,"NAYARA CAMPOS PALMA RODRIGUES",774019.05,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"CAIO PEIXOTO DE SOUZA",51487.75,"Caio Peixoto",null,"WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"PATRICIA AMARAL",57923.71,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [1,null,null,null,null,"RODOLPHO FREIRE",180172.7,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"RODOLPHO FREIRE",167303.22,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"LUCIANO TADEU DA SILVA",709517.46,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [1,null,null,null,null,"LUCIANO TADEU DA SILVA",709517.46,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [1,null,null,null,null,"MARIANA CUNHA DE FREITAS",903022.21,"Josenei Souza","josenei@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"ESTER ELISABETE BORIN",516012.7,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"ESTER ELISABETE BORIN",580514.28,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"ESTER ELISABETE BORIN",903022.21,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"VERA BUMAGNY",100000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"VERENA SANCHEZ BOHRER",516012.7,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"VERENA SANCHEZ BOHRER",838520.63,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"VERENA SANCHEZ BOHRER",516012.7,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"MATTEO GAVAZZI",962873.31,"Matteo Gavazzi",null,"BOUTIQUE DO CAMPO",2024,null,null,null,null],
  [2,null,null,null,null,"MATTEO GAVAZZI",962993.56,"Matteo Gavazzi",null,"BOUTIQUE DO CAMPO",2024,null,null,null,null],
  [2,null,null,null,null,"MATTEO GAVAZZI",962993.56,"Matteo Gavazzi",null,"BOUTIQUE DO CAMPO",2024,null,null,null,null],
  [2,null,null,null,null,"RICARDO ANTONIO DE AMORIM",295265.56,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [2,null,null,null,null,"ANDRE MACHADO KUPPER",774019.05,"Leonardo Lemos","joel@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"CAROLINA NOGUEIRA DINIZ SAMPAIO",838520.63,"Joelson",null,"SELFE BTG",2024,null,null,null,null],
  [2,null,null,null,null,"VICTOR PEREIRA MATTOS",205998,"Silene Bittencourt","silene.bittencourt@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"VICTOR PEREIRA MATTOS",195698.1,"Silene Bittencourt","silene.bittencourt@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"JOSE EDMIR SUDA",580514.28,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [2,null,null,null,null,"JOSE EDMIR SUDA",645015.87,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [2,null,null,null,null,"CONTAUDI ASSESSORIA CONTABIL LTDA",962873.31,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"CONTAUDI ASSESSORIA CONTABIL LTDA",410783.18,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"CONTAUDI ASSESSORIA CONTABIL LTDA",962993.56,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"CONTAUDI ASSESSORIA CONTABIL LTDA",256187.44,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"CONTAUDI ASSESSORIA CONTABIL LTDA",404506.48,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"CONTAUDI ASSESSORIA CONTABIL LTDA",70000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"LINEU AUGUSTO GUIMARAES FILHO",193234.23,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"LINEU AUGUSTO GUIMARAES FILHO",231077.4,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [2,null,null,null,null,"MATTEO GAVAZZI",838520.63,"Matteo Gavazzi",null,"BOUTIQUE DO CAMPO",2024,null,null,null,null],
  [2,null,null,null,null,"MATTEO GAVAZZI",903022.21,"Matteo Gavazzi",null,"BOUTIQUE DO CAMPO",2024,null,null,null,null],
  [2,null,null,null,null,"EDUARDO DE FRANCO BORGES",903022.21,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [2,null,null,null,null,"EDUARDO DE FRANCO BORGES",903022.21,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [2,null,null,null,null,"LEONARDO BELIN",100000,"João Paulo",null,"BJP",2024,null,null,null,null],
  [2,null,null,null,null,"DIARLE LUCAS MEDEIROS",100000,"João Paulo",null,"BJP",2024,null,null,null,null],
  [2,null,null,null,null,"DIARLE LUCAS MEDEIROS",100000,"João Paulo",null,"BJP",2024,null,null,null,null],
  [2,null,null,null,null,"LEONARDO BELIN",100000,"João Paulo",null,"BJP",2024,null,null,null,null],
  [2,null,null,null,null,"GUILHERME ZAIATS",100000,"João Paulo",null,"BJP",2024,null,null,null,null],
  [2,null,null,null,null,"GUILHERME ZAIATS",100000,"João Paulo",null,"BJP",2024,null,null,null,null],
  [2,null,null,null,null,"JOSIANE RICHTER",100000,"Denise Czapski","denise@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MICHEL FRANCIS LUZ",386468.46,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MICHEL FRANCIS LUZ",193234.23,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MICHEL FRANCIS LUZ",309174.77,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MICHEL FRANCIS LUZ",372291.36,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MICHEL FRANCIS LUZ",359453.72,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MICHEL FRANCIS LUZ",372291.36,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"MOACIR KENJI AOYAGUI",257645.64,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [3,null,null,null,null,"MOACIR KENJI AOYAGUI",193234.23,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [3,null,null,null,null,"MOACIR KENJI AOYAGUI",386468.46,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [3,null,null,null,null,"MOACIR KENJI AOYAGUI",385129,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [3,null,null,null,null,"MOACIR KENJI AOYAGUI",385129,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [3,null,null,null,null,"MOACIR KENJI AOYAGUI",385129,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [3,null,null,null,null,"VINICIUS TAVARES TEIXEIRA",308997,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [3,null,null,null,null,"VINICIUS TAVARES TEIXEIRA",185398.2,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [3,null,null,null,null,"VINICIUS TAVARES TEIXEIRA",308997,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",962873.31,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",962873.31,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",410783.18,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",962993.56,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",404506.48,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",404506.48,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",404506.48,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",404506.48,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"BLS MEDICAL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA",95849.41,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [3,null,null,null,null,"LUIS ALBERTO MONTEIRO",100000,"Regina Pratavieira",null,"HCI INVEST",2024,null,null,null,null],
  [3,null,null,null,null,"LUANA OLIVEIRA DE SOUZA",75000,"Regina Pratavieira",null,"HCI INVEST",2024,null,null,null,null],
  [3,null,null,null,null,"ROBERTA LOPES BARIANI",75000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"ROBERTA LOPES BARIANI",100000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [3,null,null,null,null,"ESCOLA DE MUSICA PERFORMANCE LTDA.",90000,"Glaucia Millani","glaucia@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"MARCELO BARBOSA NEGRAO",903022.21,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2024,null,null,null,null],
  [4,null,null,null,null,"MARCELO BARBOSA NEGRAO",903022.21,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2024,null,null,null,null],
  [4,null,null,null,null,"MARCELO BARBOSA NEGRAO",903022.21,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2024,null,null,null,null],
  [4,null,null,null,null,"WAGNER PALMA",903022.21,"Wagner Palma",null,"WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",404506.48,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",202253.24,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",404506.48,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",185981.68,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",185981.68,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",185981.68,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",185981.68,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",185981.68,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",185981.68,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",187056.2,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MATHEUS DE LIMA BATISTA",28502.34,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962873.31,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962873.31,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",192575.01,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",383397.64,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",397090.41,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",962993.56,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",362482.63,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",995116.89,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"MOACIR KENJI AOYAGUI",995116.89,"Bruno Perondi",null,"BJP",2024,null,null,null,null],
  [4,null,null,null,null,"LUIS ALBERTO MONTEIRO",90000,"Regina Pratavieira",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"VERENA SANCHEZ BOHRER",92990.84,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"VERENA SANCHEZ BOHRER",185981.68,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"VERENA SANCHEZ BOHRER",133611.57,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"VERENA SANCHEZ BOHRER",187056.2,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"ROSANGELA MARKMANN MESSA",100000,"Denise Czapski","denise@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [4,null,null,null,null,"EDUARDO BERTOLINI RAMOS",41412,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"EDUARDO BERTOLINI RAMOS",54770.57,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"EDUARDO BERTOLINI RAMOS",54770.57,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"EDUARDO BERTOLINI RAMOS",51765,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"EDUARDO BERTOLINI RAMOS",150000,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [4,null,null,null,null,"EDUARDO BERTOLINI RAMOS",150000,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [5,null,null,null,null,"JULIAN CLEMPER GARRIDO LOPES",1197471.88,"Diogo Kramer","diogo.kramer@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [5,null,null,null,null,"RICARDO ALBERTO CZAPSKI",2621493.61,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [5,null,null,null,null,"MARCIO DIAS BICALHO",386786.8,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [5,null,null,null,null,"PAULO HENRIQUE DA CUNHA",706222.53,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [5,null,null,null,null,"HENRIQUE DE RESENDE MENDONÇA",746075.76,"Matteo Gavazzi",null,"REFUGIOS URBANOS",2024,null,null,null,null],
  [6,null,null,null,null,"MARIA CRISTINA DE OLIVEIRA TAVARES",1688619,"Tati Leite","tatiana.leite@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [6,null,null,null,null,"MARISTELA RIBEIRO HATTY",1412025.92,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [6,null,null,null,null,"EDUARDO BERTOLINI RAMOS",470531.61,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [6,null,null,null,null,"RAFAEL BELO SILVA",1466368.24,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [6,null,null,null,null,"GEISE FERNANDA BOIGUES",307825.22,"Carla Uehara",null,"HCI INVEST",2024,null,null,null,null],
  [6,null,null,null,null,"SARITA ROSSATO MARTINHO",1533021.33,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [7,null,null,null,null,"FABIO DEMETRIO",387473.57,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [7,null,null,null,null,"MICHEL FRANCIS LUZ",501345.87,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [7,null,null,null,null,"GUILHERME FRANQUIM SACCANI",925581.46,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [7,null,null,null,null,"BARINI E COELHO LAVANDERIA",54770.57,"Claudio Ikeda","claudio.ikeda@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [8,null,null,null,null,"WM MAQUINAS AGRICOLAS",1999593.06,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [8,null,null,null,null,"MICHEL FRANCIS LUZ",1866286.84,"Diogo Giacomini",null,"WFLOW",2024,null,null,null,null],
  [8,null,null,null,null,"GUILHERME FRANQUIM SACCANI",1705506.91,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [8,null,null,null,null,"IVAN TROMBINO TAIAR",200000,"Regina Pratavieira",null,"HCI INVEST",2024,null,null,null,null],
  [8,null,null,null,null,"BASILE CHARLES MARTIN",719189.88,"Rafael Abreu","rafael.abreu@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [8,null,null,null,null,"JOSE EDMIR SUDA",733184.12,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [8,null,null,null,null,"ALICE ALVES SOUSA",1000000,null,null,"HCI INVEST",2024,null,null,null,null],
  [9,null,null,null,null,"DOUGLAS MAGALHAES JUNIOR",800421.75,null,null,"HCI INVEST",2024,null,null,null,null],
  [9,null,null,null,null,"RAFAEL BORGES BATISTA",2992533.12,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [9,null,null,null,null,"JULIO PERRELA CAMARGO",1066449.64,null,null,"HCI INVEST",2024,null,null,null,null],
  [9,null,null,null,null,"JOÃO TEZZAN",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [9,null,null,null,null,"CRISTINA RIVANDA TOLEDO",300000,null,null,"HCI INVEST",2024,null,null,null,null],
  [9,null,null,null,null,"FABIO DEMETRIO",600000,"Fabio Demetrio",null,"HCI INVEST",2024,null,null,null,null],
  [10,null,null,null,null,"NILZA ELI RODRIGUES",54770.57,null,null,"HCI INVEST",2024,null,null,null,null],
  [10,null,null,null,null,"MARCUS VINICIUS CASADEI",1666327.55,"Pedro Basso","pedro.basso@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"WM MAQUINAS AGRICOLAS",1066449.64,"Machado Junior","machado@belmont.com.br","AX HOLDER",2024,null,null,null,null],
  [10,null,null,null,null,"RAFAEL BORGES BATISTA",400000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"ALINE NOGUEIRA GUIMARAES",500000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"ROGERIO GUEDES AZEVEDO",300000,"Henrique Melgaço","henrique@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"RAFAELA PRADO LIMA",150000,null,null,"HCI INVEST",2024,null,null,null,null],
  [10,null,null,null,null,"FELIPE SILVA FRAGOSO",1500000,null,null,"HCI INVEST",2024,null,null,null,null],
  [10,null,null,null,null,"GUSTAVO GUYOT LORENCINI",260000,"Tati Ramelli",null,"WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"RODRIGO MOREIRA SARAIVA",1500000,"Claudiner Sanches","csjunior@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"ROBERTO STOLZE OLIVEIRA",260000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"MARIANNA CHOFAKIAN",400000,"Denise Czapski","denise@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"MONICA MARQUES BORGES",1000000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"BERNARDO CRUZ SALLES",1000000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"VANESSA CRISTINA",500000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"HEITOR CABRERA",670000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"FLAVIO LUIZ",150000,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"ADHEMARO FERREIRA",1800000,"Pedro Basso","pedro.basso@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"MARIA INEZ TEIXEIRA",150000,"Tiago Almeida",null,"WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"CLAUDINER JUNIOR",1500000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [10,null,null,null,null,"FABIANA OLIVEIRA",304003.47,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"DANIEL RIBAK",150000,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"IRACI RUARO",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"DEMI DALBEN",1000000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [11,null,null,null,null,"FLAVIO JUNIO LOPES",153357.6,"Amanda",null,"BANNERJET",2024,null,null,null,null],
  [11,null,null,null,null,"EDUARDO MOURA SIQUEIRA",1000000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"FABIO CALIXTO",300000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"RAFAELA COSTA MORETTI",450000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"JOÃO MATHEUS RAMOS",1000000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2024,null,null,null,null],
  [11,null,null,null,null,"ALEX MARTINS CALCINA",1000000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2024,null,null,null,null],
  [11,null,null,null,null,"CARLOS ADRIANO TEIXEIRA",450000,"Tiago Almeida",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"DIEGO MELLO DE SOUZA",1000000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2024,null,null,null,null],
  [11,null,null,null,null,"FIDAH ELMASRI",150000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"MAURICIO MARALDI",130000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"PEDRO HENRIQUE AMARAL",1000000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [11,null,null,null,null,"STEFAN WOLANSKY NEGRAO",2500000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2024,null,null,null,null],
  [11,null,null,null,null,"MMM DA SILVA TOLDOS LTDA",500000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2024,null,null,null,null],
  [11,null,null,null,null,"RONALDO GOMES DA SILVA",360000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"SOLANA MENEGHEL BOSCHILIA",360000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"CESAR AUGUSTO MACHADO",270000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"LEANDRA DALLAGNOL",150000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"FERNANDA MARQUES DE MEO",800000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [11,null,null,null,null,"JOAO FABIO BIANCHI",1000000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [12,null,null,null,null,"MAURICIO LORENZI",75000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [12,null,null,null,null,"FIDAH ELMASRI",150000,"Leonardo Lemos",null,"WFLOW",2024,null,null,null,null],
  [12,null,null,null,null,"STEFAN WOLANSKY NEGRAO",2500000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2024,null,null,null,null],
  [12,null,null,null,null,"LARISSA SILVA FURTADO",1600000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2024,null,null,null,null],
  [12,null,null,null,null,"MATHEUS HENRIQUE MORAIS",53866.66,"Amanda",null,"BANNERJET",2024,null,null,null,null],
  [12,null,null,null,null,"SERGIO LUIZ VASSELAI",150000,"Diogo Kramer","diogo.kramer@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [12,null,null,null,null,"RICHARD CARNEIRO RIOS",467733.32,"Diego Collim",null,"BANNERJET",2024,null,null,null,null],
  [12,null,null,null,null,"CHRISTIAN MARTINS OPATRNY",150000,"Fabio Zanini","fabio.zanini@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [12,null,null,null,null,"SEVERINO BATISTA DA SILVA",260000,"Larissa Bernardes",null,"LBL SERVICOS",2024,null,null,null,null],
  [12,null,null,null,null,"ANGELICA RAMOS BONI",200843.29,"Bernardo Zilber","bernardo@wflowinvest.com","WFLOW",2024,null,null,null,null],
  [1,null,null,null,null,"LUKAS SCERVIANINAS",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUKAS SCERVIANINAS",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUKAS SCERVIANINAS",140000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUKAS SCERVIANINAS",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"ANDRE ROSA DOS SANTOS",100000,"Ricardo Barquetta","ricardo.barquetta@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"RICARDO TAKAO KAYANO",120000,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"FERNANDA  MARCHI MARCONDES PELEGRINI",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,null,null,null,null,"MARIO SERGIO RIZK DE ABREU",100000,"Paulo Saad","paulo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"ESTEFANIA FERRAZZINI PAULIN",150000,"Guilherme Viveiros","guilherme@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",130000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",120000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",150000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",150000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",150000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",150000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"BRUNO PORTEIRO PROSPERO",150000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",130000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",120000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"IRACI RUARO TAGLIANI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUCAS PORTEIRO PROSPERO",130000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUCAS PORTEIRO PROSPERO",130000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUCAS PORTEIRO PROSPERO",120000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"LUCAS PORTEIRO PROSPERO",120000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"TIAGO NICEZIO DE ALMEIDA",100000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",150000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",130000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",150000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",150000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",150000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [1,null,null,null,null,"CARINA SANTA MARIA",150000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"CELY GISELE DOS REIS",120000,"Jamil Reis","jamil@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"CELY GISELE DOS REIS",120000,"Jamil Reis","jamil@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"FABIO BELLIZZI FERREIRA",150000,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [2,null,null,null,null,"FABIO BELLIZZI FERREIRA",150000,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [2,null,null,null,null,"FABIO BELLIZZI FERREIRA",150000,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [2,null,null,null,null,"FABIO BELLIZZI FERREIRA",150000,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [2,null,null,null,null,"MARIANA GOBATTO DE SOUZA",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"MARIANA GOBATTO DE SOUZA",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"COFEL MAQUINAS E EQUIPAMENTOS LTDA",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"COFEL MAQUINAS E EQUIPAMENTOS LTDA",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"COFEL MAQUINAS E EQUIPAMENTOS LTDA",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"ZILDA CASTANHO ROSA CARRION CARRACEDO",120000,"Caristhon Azevedo","caristhon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"ZILDA CASTANHO ROSA CARRION CARRACEDO",120000,"Caristhon Azevedo","caristhon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"ZILDA CASTANHO ROSA CARRION CARRACEDO",140000,"Caristhon Azevedo","caristhon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"ZILDA CASTANHO ROSA CARRION CARRACEDO",120000,"Caristhon Azevedo","caristhon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME RIBAS",150000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"LUCIANA APARECIDA DOS SANTOS",150000,"Jamil Reis","jamil@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"LUCIANA APARECIDA DOS SANTOS",150000,"Jamil Reis","jamil@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"LUCIANA APARECIDA DOS SANTOS",150000,"Jamil Reis","jamil@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"LUCIANA APARECIDA DOS SANTOS",150000,"Jamil Reis","jamil@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",140000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",140000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"ASSOCIAÇAO GOTAS DE ORVALHO",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"ASSOCIAÇAO GOTAS DE ORVALHO",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"ASSOCIAÇAO GOTAS DE ORVALHO",120000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",150000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",150000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",130000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",150000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",120000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",150000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [2,null,null,null,null,"GUILHERME AKIITI IKEDA",150000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [3,null,null,null,null,"GUILHERME AKIITI IKEDA",500000,"Gabriel Bergamini",null,"SELFE BTG",2025,null,null,null,null],
  [3,null,null,null,null,"STEFAN WOLANSKY NEGRAO",2500000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [3,null,null,null,null,"CLARISSA MACHADO ODLOAK HOSOUME",2500000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [3,null,null,null,null,"CARLOS ALEXANDRE BERTASO",500000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [3,null,null,null,null,"ANNA RACHEL ALGAZI",280000,"Claudiner Junior","csjunior@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [3,null,null,null,null,"BRUNO FELIPE SOUZA",1000000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [3,null,null,null,null,"THIAGO NEPOMUCENO DE CARVALHO",1000000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [3,null,null,null,null,"RENATO MAGNO DA SILVA",135421,"Wekslei Gomes","wekslei@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [4,null,null,null,null,"EDVAR DA COSTA GALVAO FILHO",840000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [4,null,null,null,null,"SILVANA MARTINS GALVAO",1560000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [4,null,null,null,null,"JULIA ARRUDA GALVÃO",360000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [4,null,null,null,null,"LUISA ARRUDA GALVÃO",360000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [4,null,null,null,null,"DANIEL CENDON DURAN",2000000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [4,null,null,null,null,"FABIANO PENELUPI MELO",600000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [4,null,null,null,null,"DENISE RISAE OKUMA",250000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [4,null,null,null,null,"ALAN VILELA DE SOUZA",300000,"Tiago Nicezio",null,"WFLOW",2025,null,null,null,null],
  [5,null,null,null,null,"MARCOS MANOEL PEREIRA",500000,"Rogerio Castilho","rogeriocastilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [5,null,null,null,null,"FLAVIA TIMOTHEO PEREIRA",156255,"Ricardo Barquetta","ricardo.barquetta@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [5,null,null,null,null,"MAURICIO LUIS DE LORENZI",145838,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [5,null,null,null,null,"PRISCILA EVELEYN BARROS",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [5,null,null,null,null,"CARLOS RIBAS",500000,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [5,null,null,null,null,"FABIANO PENTEADO",500000,"Andrea Tonhao",null,"SELFE BTG",2025,null,null,null,null],
  [5,null,null,null,null,"MARCUS MATOS",1000000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [5,null,null,null,null,"JOEL FIGUEREDO",200000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [5,null,null,null,null,"HELOISA DE MOURA RIBEIRO",1350000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"MARCELO RODRIGO WECKERLIN",500000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [6,null,null,null,null,"MELANIA MARIA DANIELLI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"MELANIA MARIA DANIELLI",140000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"MELANIA MARIA DANIELLI",150000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"MELANIA MARIA DANIELLI",120000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"MELANIA MARIA DANIELLI",140000,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CESAR AUGUSTO CAMPANA DOS SANTOS",140000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"SCARLAT CAROLINA DE ALMEIDA",50000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",120000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",130000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"CALLIDUS ADMINISTRADORA DE PARTICIPACOES SOCIETARIAS LTDA",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"ROBERTO AVILA DOS SANTOS JUNIOR",120000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"ROBERTO AVILA DOS SANTOS JUNIOR",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"ROBERTO AVILA DOS SANTOS JUNIOR",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"ROBERTO AVILA DOS SANTOS JUNIOR",140000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"ROBERTO AVILA DOS SANTOS JUNIOR",120000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"ROBERTO AVILA DOS SANTOS JUNIOR",120000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",140000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",150000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",150000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",150000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",130000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",150000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",140000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",120000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"PAULA NIVEA DO MONTE CARMELO LUCHINI",150000,"Ricardo Czapski","ricardo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"VINICIUS AUGUSTO PASSARELLA DE MELO",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"VINICIUS AUGUSTO PASSARELLA DE MELO",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"VINICIUS AUGUSTO PASSARELLA DE MELO",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"VINICIUS AUGUSTO PASSARELLA DE MELO",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [6,null,null,null,null,"VINICIUS AUGUSTO PASSARELLA DE MELO",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"MANOELA C. M. D. S.",120000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"MANOELA C. M. D. S.",120000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",120000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",130000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LUISA A. D. C. G. V. M.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",150000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",150000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",150000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",120000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",130000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",150000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"LIDYANE F. P.",150000,"Luiz Gustavo","lgfreitas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"NICOLUCI &. N. -. A. E. P. L.",150000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",130000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",120000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",150000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",150000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",150000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",150000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"MARCELO R. W.",150000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [7,null,null,null,null,"OLIVIA M. E. P.",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"OLIVIA M. E. P.",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"OLIVIA M. E. P.",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"OLIVIA M. E. P.",140000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"OLIVIA M. E. P.",150000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [7,null,null,null,null,"OLIVIA M. E. P.",150000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",130000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",130000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCOS V. G. T.",150000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"ANDERSON C. S.",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"ANDERSON C. S.",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"ANDERSON C. S.",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"ANDERSON C. S.",150000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"MARCEL S. D. S. M.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCEL S. D. S. M.",140000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCEL S. D. S. M.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"MARCEL S. D. S. M.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"RENAN S. D. S. M.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"RENAN S. D. S. M.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"NILSON B. T. J.",120000,"Marden",null,"BANNERJET",2025,null,null,null,null],
  [8,null,null,null,null,"NILSON B. T. J.",130000,"Marden",null,"BANNERJET",2025,null,null,null,null],
  [8,null,null,null,null,"RENAN S. D. S. M.",120000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"RENAN S. D. S. M.",140000,"Joel Figueredo","joel@wflowinvest.com","JTDK",2025,null,null,null,null],
  [8,null,null,null,null,"NILSON B. T. J.",150000,"Marden",null,"BANNERJET",2025,null,null,null,null],
  [8,null,null,null,null,"NILSON B. T. J.",150000,"Marden",null,"BANNERJET",2025,null,null,null,null],
  [8,null,null,null,null,"NILSON B. T. J.",150000,"Marden",null,"BANNERJET",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"GLAUCO B.",150000,"Karina Cassalho","karina.cassalho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"LUIS G. M.",150000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"LUIS G. M.",130000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"LUIS G. M.",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"LEONARDO B.",104170,"João Paulo",null,"AX HOLDER",2025,null,null,null,null],
  [8,null,null,null,null,"JANAINA F. D. V.",130000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"JANAINA F. D. V.",130000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"JANAINA F. D. V.",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [8,null,null,null,null,"JANAINA F. D. V.",120000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [9,null,null,null,null,"GUSTAVO MARQUES DE CASTRO",274067,"Diogo Giacomini",null,"WFLOW",2025,null,null,null,null],
  [10,null,null,null,null,"FRANCIANE DE FATIMA LOPES PONTES",600000,"Matheus Heckler","joaomatheus_heckler@outlook.com","HECKLER SERVIÇOS",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO SUNE CHRISTIANO",146788.99,"Fernando Alarcon","fernando.alarcon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO SUNE CHRISTIANO",146788.99,"Fernando Alarcon","fernando.alarcon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LUCIANO GOULART PAZ",294358.4,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LUCIANO GOULART PAZ",300000,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LUCIANO GOULART PAZ",210000,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LUCIANO GOULART PAZ",210000,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",981679.94,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",194864.3,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",188633.93,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",188633.93,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",188633.93,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",188633.93,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO DE FRANCO BORGES",94316.97,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"VINICIUS GRACZCKI LUPATINI",560959.98,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"VINICIUS GRACZCKI LUPATINI",560959.98,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"VINICIUS GRACZCKI LUPATINI",560959.98,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"VINICIUS GRACZCKI LUPATINI",560959.98,"Machado Junior","machado@belmont.com.br","AX HOLDER",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO SUNE CHRISTIANO",150000,"Fernando Alarcon","fernando.alarcon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO SUNE CHRISTIANO",150000,"Fernando Alarcon","fernando.alarcon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO SUNE CHRISTIANO",150000,"Fernando Alarcon","fernando.alarcon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"EDUARDO SUNE CHRISTIANO",150000,"Fernando Alarcon","fernando.alarcon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RAFAEL MATUSCHKA MACEDO MELLO",300000,"Lucas Barbosa/Rafael Matuschka","lucas@wflowinvest.com/rafael.mello@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RAFAEL MATUSCHKA MACEDO MELLO",300000,"Lucas Barbosa/Rafael Matuschka","lucas@wflowinvest.com/rafael.mello@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RAFAEL MATUSCHKA MACEDO MELLO",200000,"Lucas Barbosa/Rafael Matuschka","lucas@wflowinvest.com/rafael.mello@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDRE JESZENSKY FILHO",300000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDRE JESZENSKY FILHO",300000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RAFAEL MATUSCHKA MACEDO MELLO",200000,"Lucas Barbosa/Rafael Matuschka","lucas@wflowinvest.com/rafael.mello@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDRE JESZENSKY FILHO",300000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDRE JESZENSKY FILHO",300000,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"KARINA BARQUETTA DE ARAUJO OLIVIO",120000,"Ricardo Barquetta","ricardo.barquetta@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ENZO ONADY ABI RACHED",200000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ENZO ONADY ABI RACHED",200000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LUCAS HENRIQUE BARBOSA",315384,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCOS DE SOUZA AZEVEDO",300000,"Fabio Zogaib","zg@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RENATO DE ARRUDA HELLMEISTER",150000,"Renato Hellmeister","renato.hellmeister@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"WILSON CARLOS FREIRE",315384,"Lucas Barbosa","lucas@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"DANIEL FRANKLIN PEREIRA FREITAS",200000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LZ CARVALHO ADMINISTRACAO E PARTICIPACOES LTDA",701199.96,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ZORAIDE CUNHA DE CARVALHO",87517.8,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ZORAIDE CUNHA DE CARVALHO",87517.8,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ZORAIDE CUNHA DE CARVALHO",87517.8,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ZORAIDE CUNHA DE CARVALHO",87517.8,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"BRUNO ALCANTARA DA COSTA PENNA",252307.2,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"BRUNO ALCANTARA DA COSTA PENNA",252307.2,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"BRUNO ALCANTARA DA COSTA PENNA",252307.2,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"BRUNO ALCANTARA DA COSTA PENNA",252307.2,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RODRIGO SALMAN ROCHA PINTO",250000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RODRIGO SALMAN ROCHA PINTO",250000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RODRIGO SALMAN ROCHA PINTO",250000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RODRIGO SALMAN ROCHA PINTO",250000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ERICK GOUVEA SOARES",250000,"Sabrina Costa","sabrina@jtdkinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ERICK GOUVEA SOARES",250000,"Sabrina Costa","sabrina@jtdkinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ERICK GOUVEA SOARES",250000,"Sabrina Costa","sabrina@jtdkinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ERICK GOUVEA SOARES",250000,"Sabrina Costa","sabrina@jtdkinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARLEI RAQUEL DANIELLI",911559.95,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ALEXANDRA PEREIRA SPINA",250000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ALEXANDRA PEREIRA SPINA",250000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",701199.96,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",701199.96,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",250000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",250000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",315384,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",315384,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",315384,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",315384,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",315384,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ANDREIA MARQUES BORGES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RUANN BARBOSA TEIXEIRA",200000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RUANN BARBOSA TEIXEIRA",200000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"DENISE AGUILAR COSTA",250000,"Paulo Saad","paulo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"DENISE AGUILAR COSTA",250000,"Paulo Saad","paulo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"DENISE AGUILAR COSTA",250000,"Paulo Saad","paulo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"DENISE AGUILAR COSTA",250000,"Paulo Saad","paulo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LAURO KATSUO WATANABE",100000,"Henrique Melgaço","henrique@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"LAURO KATSUO WATANABE",100000,"Henrique Melgaço","henrique@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MAURICIO ROSSI GUIMARAES",841439.96,"Savio Melo","saviomelo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MAURICIO ROSSI GUIMARAES",841439.96,"Savio Melo","saviomelo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MAURICIO ROSSI GUIMARAES",841439.96,"Savio Melo","saviomelo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MAURICIO ROSSI GUIMARAES",841439.96,"Savio Melo","saviomelo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"JANUARIO BATISTA DO AMARAL NETO",150000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"RONALDO VIEIRA MARTINS",300000,"Fernando Salomon","fernando.salomon@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARLEI RAQUEL DANIELLI",911559.95,"Marlei Danielli","marleidanielli@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"MARCO ANTONIO VON HELDE DOS SANTOS",315384,"Alexandre Von Helde","alexandre.vonhelde@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ALEXANDRE VON HELDE DOS SANTOS",315384,"Alexandre Von Helde","alexandre.vonhelde@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"GUILHERME FRANQUIM SACCANI",841439.96,"Joel Figueredo","joel@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"ELISIANE GADELHA DIAS OLIVEIRA",87517.8,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"GUSTAVO STOLZE OLIVEIRA",250000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"PAULO SERGIO SAAD",560959.98,"Paulo Saad","paulo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"JOEL CARVALHO DE FIGUEREDO",981679.94,"Joel Figueredo","joel@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"JOEL CARVALHO DE FIGUEREDO",560959.98,"Joel Figueredo","joel@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [11,null,null,null,null,"SABRINA CAROLINE ELIAS DA COSTA",50000,"Sabrina Costa","sabrina@jtdkinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"VITOR RAMOS SILVA",250000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"VITOR RAMOS SILVA",250000,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"VITOR RAMOS SILVA",260444.5,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"VITOR RAMOS SILVA",262820,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",150000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FERNANDO DIAS RODRIGUES",200000,"Oswaldo Borges","oswaldo@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"MARCELO DELGADO",187520.04,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"MARCELO DELGADO",187520.04,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"FABIO SCHIAVONE ZANINI",71108.21,"Fabio Zanini","fabio.zanini@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"LUIZ HENRIQUE YUJI DELGADO ODA",187520.04,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"LUIZ HENRIQUE YUJI DELGADO ODA",187520.04,"Hamilton Oda","hamilton@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"JORGE AMÉRICO MARFIM STAKOWIAK",82047.94,"Claudio Ikeda","claudio.ikeda@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"CESAR AUGUSTO DUENAS MORAN",145000,"Glaucia Millani","glaucia@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"CAROLINA CORTESE COELHO",90000,"Diogo Kramer","diogo.kramer@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"MAYARA LUIZE VICENTAINER",199743.2,"Diogo Kramer","diogo.kramer@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"MAYARA LUIZE VICENTAINER",199743.2,"Diogo Kramer","diogo.kramer@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"RICARDO DAGLIO COLOMBANI UCHOA CAVALCANTI ALMEIDA",199743.2,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"RICARDO DAGLIO COLOMBANI UCHOA CAVALCANTI ALMEIDA",199743.2,"Guilherme Cunha","guilherme.cunha@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"GILBERTO LYRIO NETO",250000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"GILBERTO LYRIO NETO",250000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"GILBERTO LYRIO NETO",250000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"GILBERTO LYRIO NETO",250000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"GILBERTO LYRIO NETO",250000,"Roberto Stolze","roberto.stolze@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"ROGERIO VEROLEZ DE CASTILHO",150000,"Rogerio Castilho","rogerio.castilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"ROGERIO VEROLEZ DE CASTILHO",150000,"Rogerio Castilho","rogerio.castilho@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"MAISA ISABEL D ELIA",125000,"Wagner Palma","wagner.palma@wflowadv.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"DIEGO MEDINA OSORIO",70000,"Tati Leite","tatiana.leite@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"DIEGO MEDINA OSORIO",60000,"Tati Leite","tatiana.leite@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"GUILHERME FRANQUIM SACCANI",560959.98,"Joel Figueredo","joel@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"DIEGO MEDINA OSORIO",70000,"Tati Leite","tatiana.leite@wflowinvest.com","WFLOW",2025,null,null,null,null],
  [12,null,null,null,null,"MARCIO BARBOSA NEGRÃO",29000000,"Fernanda Sykora","fer_sy@hotmail.com","SELFE BTG",2025,null,null,null,null],
  [1,"IMÓVEIS","001039",1143,1979.69,"LUIZ FERNANDO FERREIRA DELAZARI",392873.49,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.22],
  [1,"IMÓVEIS","001039",3146,1979.69,"LUIZ FERNANDO FERREIRA DELAZARI",392873.49,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.22],
  [1,"IMÓVEIS","001053",534,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",1435,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",2865,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",2340,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",2587,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",3886,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",3104,382.05,"LUIZ FERNANDO FERREIRA DELAZARI",150000,"Henrique Melgaço/Marcelo Nacle","henrique@wflowinvest.com/marcelo.nacle@wflowinvest.com","WFLOW",2026,"PF","PR","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",687,993.2,"MIGUEL BARCELLOS SAMPAIO MORENO",200000,"Rafael Matuschka/ Lucas Barbosa","rafael.mello@wflowinvest.com/lucas@wflowinvest.com","WFLOW",2026,"PF","RJ","Cheia",0.15],
  [1,"IMÓVEIS","001053",802,993.2,"MIGUEL BARCELLOS SAMPAIO MORENO",200000,"Rafael Matuschka/ Lucas Barbosa","rafael.mello@wflowinvest.com/lucas@wflowinvest.com","WFLOW",2026,"PF","RJ","Cheia",0.15],
  [1,"IMÓVEIS","001053",1964,993.2,"MIGUEL BARCELLOS SAMPAIO MORENO",200000,"Rafael Matuschka/ Lucas Barbosa","rafael.mello@wflowinvest.com/lucas@wflowinvest.com","WFLOW",2026,"PF","RJ","Cheia",0.15],
  [1,"IMÓVEIS","001053",2781,507,"BETANIA DA SILVA ROCHA",200000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2026,"PF","SP","Reduzida 50%",0.18],
  [1,"IMÓVEIS","001053",1130,405.6,"BETANIA DA SILVA ROCHA",160000,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2026,"PF","SP","Reduzida 50%",0.18],
  [2,"IMÓVEIS","001038",3257,5194.07,"JACKSON ZENI CZARNESKI",981679.94,"Nycolas Palma","nycolas.palma@wflowinvest.com","WFLOW",2026,"PF","SP","Reduzida 50%",0.22],
  [2,"IMÓVEIS","001038",2502,3710.04,"NICOLE BUMAGNY",701199.96,"Marcus Matos","marcusmatos@wflowinvest.com","WFLOW",2026,"PF","BA","Reduzida 50%",0.22]
];

async function seedProducao() {
  const { rows: [{ count }] } = await db.query('SELECT COUNT(*) FROM producao');
  if (parseInt(count) > 0) {
    console.log(`seed_producao: tabela já tem ${count} registros, pulando.`);
    return;
  }
  for (const r of ROWS) {
    await db.query(
      `INSERT INTO producao (mes, modalidade, grupo, cota, parcela, cliente, valor_do_bem, assessor, email_assessor, escritorio, ano, natureza_sujeito, uf, tipo_produto, taxa_adm)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,
      r
    );
  }
  console.log('seed_producao: 667 registros inseridos!');
}

module.exports = seedProducao;

if (require.main === module) {
  seedProducao().then(() => process.exit(0)).catch(err => {
    console.error('Erro seed_producao:', err);
    process.exit(1);
  });
}
